language: rust
rust    : nightly

install:
  - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
  - npm install -g sass
  - npm install -g clean-css-cli

script:
  - make

after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  sudo pip install ghp-import &&
  ghp-import -n public -b gh-pages &&
  git checkout gh-pages &&
  git push -fq https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages